"""Custom agent example — shows how to write and run a bespoke agent."""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parents[2]))

from agents.base import BaseAgent
from agents.registry import AgentRegistry
from models import AgentCapability, AgentMetadata, DocumentArtifact
from models.execution import ExecutionContext


class SummaryAgent(BaseAgent):
    """Custom agent that produces a project summary artifact."""

    def __init__(self) -> None:
        super().__init__(
            metadata=AgentMetadata(
                name='summary_agent',
                version='1.0.0',
                description='Produces a one-page project summary',
                category='planning',
                outputs=['project_summary'],
            ),
            capabilities=[AgentCapability(name='summarise', description='Summarise project scope')],
        )

    def _execute(self, context: ExecutionContext) -> list:
        idea = context.inputs.get('idea', 'A new project')
        content = f'# Project Summary\n\nIdea: {idea}\n\nGenerated by SummaryAgent.'
        return [self.create_artifact(context, 'project_summary', content, DocumentArtifact)]


def main() -> None:
    registry = AgentRegistry()
    registry.register(SummaryAgent())

    agent = registry.resolve('summary_agent')
    from models.execution import ExecutionContext, ExecutionState
    context = ExecutionContext(
        project_id='demo',
        workflow_name='custom-demo',
        step_name='summarise',
        inputs={'idea': 'An AI-powered recipe recommendation app'},
    )

    artifacts = agent.execute(context)
    for artifact in artifacts:
        print(f'[{artifact.name}]\n{artifact.content}\n')


if __name__ == '__main__':
    main()
